### PR TITLE
Fix additional dialog in quest "Toraimarai Turmoil"

### LINKED ISSUE #2067: Windurst Quest "Toraimarai Turmoil" Additional lines of dialogue
<a href="https://github.com/eyes-and-brain"></img></a> **Issue by [eyes-and-brain](https://github.com/eyes-and-brain)**
_Sunday Oct 11, 2020 at 11:04:25_
_Originally opened as: project-topaz/topaz - Issue 1324_

----

**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

If the quest "Toraimarai Turmoil" is QUEST_ACCEPTED the message of the NPC should change.

- Leepe-Hoppe
https://github.com/project-topaz/topaz/blob/daf504aa7a7dae2f39045140739047459ac3865c/scripts/zones/Windurst_Waters/npcs/Leepe-Hoppe.lua#L122-L124
The behavior at the moment, you will see the event ID "345".  (L123)
```
    local turmoil = player:getQuestStatus(WINDURST, tpz.quest.id.windurst.TORAIMARAI_TURMOIL)

    elseif (turmoil == QUEST_ACCEPTED) then
        player:startEvent(790, 0, tpz.ki.RHINOSTERY_CERTIFICATE)
    else
        player:startEvent(345) -- Standard Dialogue?
    end
```
Add a serif pattern to the lowest priority position of the condition.

- Yoran-Oran
https://github.com/project-topaz/topaz/blob/daf504aa7a7dae2f39045140739047459ac3865c/scripts/zones/Windurst_Walls/npcs/Yoran-Oran.lua#L69-L71
The behavior at the moment, you will see the event ID "245".  (70)
```
    local turmoil = player:getQuestStatus(WINDURST, tpz.quest.id.windurst.TORAIMARAI_TURMOIL)

    elseif (turmoil == QUEST_ACCEPTED) then
        player:startEvent(392)
    else
        player:startEvent(245)
    end
```
Add a serif pattern to the lowest priority position of the condition.

- Polikal-Ramikal
https://github.com/project-topaz/topaz/blob/daf504aa7a7dae2f39045140739047459ac3865c/scripts/zones/Windurst_Walls/npcs/Polikal-Ramikal.lua#L12-L14
```
function onTrigger(player, npc)
    local turmoil = player:getQuestStatus(WINDURST, tpz.quest.id.windurst.TORAIMARAI_TURMOIL)
    if (turmoil == QUEST_ACCEPTED) then
        player:startEvent(391)
    else
        player:startEvent(320)
    end
end
```

### PR DESCRIPTION
**Pull request by ghost**
**_I affirm:_**
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/topaz-next/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have read the [Contributing Guide](https://github.com/topaz-next/topaz/blob/release/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md)
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

**_Temporary_**:
- [x] that I understand there are large refactoring efforts going on right now, that these efforts touch every single Lua script and binding, and that my pull request might get put on hold to ensure there are not any conflicts with the refactoring work

Fixes #2067

### CODE REVIEW

File: scripts/zones/Windurst_Waters/npcs/Leepe-Hoppe.lua [hunk 1]
```diff
@@ -27,6 +27,7 @@ entity.onTrigger = function(player, npc)
     local MissionStatus = player:getCharVar("MissionStatus")
     local tuningIn = player:getQuestStatus(tpz.quest.log_id.WINDURST, tpz.quest.id.windurst.TUNING_IN)
     local tuningOut = player:getQuestStatus(tpz.quest.log_id.WINDURST, tpz.quest.id.windurst.TUNING_OUT)
+    local turmoil = player:getQuestStatus(tpz.quest.log_id.WINDURST, tpz.quest.id.windurst.TORAIMARAI_TURMOIL)
```
Comment (wrenffxi) [inline scripts/zones/Windurst_Waters/npcs/Leepe-Hoppe.lua:32]: file is missing
```
require("scripts/globals/quests")
require("scripts/globals/titles")
```

not your fault; these should have been required already, before your edits.  notice tpz.title is used on line 179 and elsewhere

File: scripts/zones/Windurst_Walls/npcs/Polikal-Ramikal.lua [hunk 2]
```diff
@@ -9,7 +9,13 @@ entity.onTrade = function(player, npc, trade)
 end
 
 entity.onTrigger = function(player, npc)
-    player:startEvent(320)
+    local turmoil = player:getQuestStatus(tpz.quest.log_id.WINDURST, tpz.quest.id.windurst.TORAIMARAI_TURMOIL)
```
Comment (wrenffxi) [inline scripts/zones/Windurst_Walls/npcs/Polikal-Ramikal.lua:14]: file needs
```
require("scripts/globals/quests")
```

now that it uses tpz.quest and QUEST_ACCEPTED

**Review by wrenffxi — CHANGES_REQUESTED** [review]

**Review by wrenffxi — APPROVED** [review]
