### PR TITLE
Fix additional dialog and ferry cost for quest "His Name is Valgeir"

### LINKED ISSUE #2068: Mhaura Quest "His Name is Valgeir" The "Ship bound for Selbina" fare should be free while your quest is being ordered.
<a href="https://github.com/eyes-and-brain"></img></a> **Issue by [eyes-and-brain](https://github.com/eyes-and-brain)**
_Sunday Oct 11, 2020 at 12:50:10_
_Originally opened as: project-topaz/topaz - Issue 1325_

----

**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The "Ship bound for Selbina" fare should be free while your quest is being ordered.

https://github.com/project-topaz/topaz/blob/b5203ef0e1025e400888bb8c57ae80be43ce5d9e/scripts/zones/Mhaura/npcs/Felisa.lua#L10-L18
The following modifications will free up the fare.
```
require("scripts/globals/keyitems")
require("scripts/globals/quests")

function onTrigger(player, npc)
    if (player:getZPos() > 38.5) then
      if (player:getQuestStatus(OTHER_AREAS_LOG, tpz.quest.id.otherAreas.HIS_NAME_IS_VALGEIR) == QUEST_ACCEPTED and player:hasKeyItem(tpz.ki.ARAGONEU_PIZZA)) then
          player:startEvent(230)
      else
          player:startEvent(221, player:getGil(), 100)
      end
    else
        player:startEvent(235)
    end
end
```

### PR DESCRIPTION
**Pull request by ghost**
**_I affirm:_**
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/topaz-next/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have read the [Contributing Guide](https://github.com/topaz-next/topaz/blob/release/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md)
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

**_Temporary_**:
- [x] that I understand there are large refactoring efforts going on right now, that these efforts touch every single Lua script and binding, and that my pull request might get put on hold to ensure there are not any conflicts with the refactoring work

Fixes #2068

### CODE REVIEW

File: scripts/zones/Mhaura/npcs/Felisa.lua [hunk 1]
```diff
@@ -11,7 +11,13 @@ end
 entity.onTrigger = function(player, npc)
 
     if (player:getZPos() > 38.5) then
-        player:startEvent(221, player:getGil(), 100)
+        if player:getQuestStatus(OTHER_AREAS_LOG, tpz.quest.id.otherAreas.HIS_NAME_IS_VALGEIR) == QUEST_ACCEPTED and
```
Comment (wrenffxi) [inline scripts/zones/Mhaura/npcs/Felisa.lua]: indentation, and changing log reference:

```
if
    player:getQuestStatus(tpz.quest.log_id.OTHER_AREAS, tpz.quest.id.otherAreas.HIS_NAME_IS_VALGEIR) == QUEST_ACCEPTED and
    player:hasKeyItem(tpz.ki.ARAGONEU_PIZZA)
then
```

**Review by wrenffxi — CHANGES_REQUESTED** [review]

File: scripts/zones/Mhaura/npcs/Felisa.lua (hunk 1 above)
Comment (ghost) [reply scripts/zones/Mhaura/npcs/Felisa.lua]: Definitely on the formatting.  Can you clarify on the log reference?  `OTHER_AREAS_LOG` is specific to the table, whereas this is passing an int value.  `tpz.quest.log_id` only has an `OTHER_AREAS` reference.

Also, that quest would have been completely broken to this point, as getQuestStatus only accepts (int, int) after the sol refactor.

Ref: `uint8 CLuaBaseEntity::getQuestStatus(uint8 questLogID, uint16 questID)`

Comment (wrenffxi) [reply scripts/zones/Mhaura/npcs/Felisa.lua]: In the code you're adding in this PR, `if player:getQuestStatus(OTHER_AREAS_LOG, ...` is passing OTHER_AREAS_LOG, which is table.

In my suggested code, `player:getQuestStatus(tpz.quest.log_id.OTHER_AREAS, ...` is passing an int (4), which the binding should accept.

Comment (ghost) [reply scripts/zones/Mhaura/npcs/Felisa.lua]: Doh! I thought I fixed that.  Absolutely correct.

**Review by wrenffxi — APPROVED** [review]

**Comment by wrenffxi** [comment]
Missed this on my first review:

```
-----------------------------------
-- Area: Mhaura
--  NPC: Felisa
-- Admits players to the dock in Mhaura.
-----------------------------------
local entity = {}
```

to

```
-----------------------------------
-- Area: Mhaura
--  NPC: Felisa
-- Admits players to the dock in Mhaura.
-----------------------------------
require("scripts/globals/keyitems")
require("scripts/globals/quests")
-----------------------------------
local entity = {}
```

**Review by wrenffxi — APPROVED** [review]
