### PR TITLE
Fix additional dialog for RoV Mission "The Path Untraveled"

### LINKED ISSUE #2040: RoV Missions "The Path Untraveled" Additional lines of dialogue
<a href="https://github.com/eyes-and-brain"></img></a> **Issue by [eyes-and-brain](https://github.com/eyes-and-brain)**
_Friday Oct 09, 2020 at 12:21:22_
_Originally opened as: project-topaz/topaz - Issue 1297_

----

**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

While the mission is in progress, the NPC's dialogue should change.

https://github.com/project-topaz/topaz/blob/bdef7042ccc1791f4e3ae330255fbc5c5b87f1f0/scripts/zones/Norg/npcs/Heillal.lua#L10-L12

```
function onTrigger(player, npc)
    local RhapsodiesMission = player:getCurrentMission(ROV)
    if RhapsodiesMission == tpz.mission.id.rov.THE_BEGINNING then
        player:startEvent(281)
    else
        player:startEvent(64)
    end
end
```

https://github.com/project-topaz/topaz/blob/bdef7042ccc1791f4e3ae330255fbc5c5b87f1f0/scripts/zones/Norg/npcs/Comitiolus.lua#L17-L28
```
function onTrigger(player, npc)
    local tuningOutProgress = player:getCharVar("TuningOut_Progress")
    local RhapsodiesMission = player:getCurrentMission(ROV)

    if tuningOutProgress == 6 then
        player:startEvent(206) -- Declines request to speak to Kamui
    elseif tuningOutProgress == 7 then
        player:startEvent(208) -- Repeat hint for player to go to Beaucedine Glacier
    elseif RhapsodiesMission == tpz.mission.id.rov.THE_BEGINNING then
        player:startEvent(6)
    else
        player:startEvent(72)
    end
end
```

The NPC "Gilgamesh" becomes unresponsive.

https://github.com/project-topaz/topaz/blob/bdef7042ccc1791f4e3ae330255fbc5c5b87f1f0/scripts/zones/Norg/npcs/Gilgamesh.lua#L19-L43

```
    elseif player:getCurrentMission(ROV) == tpz.mission.id.rov.THE_PATH_UNTRAVELED then
        player:startEvent(263)
    end
```

### PR DESCRIPTION
**Pull request by ghost**
**_I affirm:_**
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/topaz-next/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have read the [Contributing Guide](https://github.com/topaz-next/topaz/blob/release/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md)
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

**_Temporary_**:
- [x] that I understand there are large refactoring efforts going on right now, that these efforts touch every single Lua script and binding, and that my pull request might get put on hold to ensure there are not any conflicts with the refactoring work

Fixes #2040

### CODE REVIEW

File: scripts/zones/Norg/npcs/Comitiolus.lua [hunk 1]
```diff
@@ -23,7 +23,8 @@ entity.onTrigger = function(player, npc)
         player:startEvent(206) -- Declines request to speak to Kamui
     elseif tuningOutProgress == 7 then
         player:startEvent(208) -- Repeat hint for player to go to Beaucedine Glacier
-
+    elseif player:getCurrentMission(ROV) == tpz.mission.id.rov.THE_BEGINNING then
```
Comment (wrenffxi) [inline scripts/zones/Norg/npcs/Comitiolus.lua:27]:
```
require("scripts/globals/missions")
```

File: scripts/zones/Norg/npcs/Heillal.lua [hunk 2]
```diff
@@ -9,7 +9,11 @@ entity.onTrade = function(player, npc, trade)
 end
 
 entity.onTrigger = function(player, npc)
-    player:startEvent(64)
+    if player:getCurrentMission(ROV) == tpz.mission.id.rov.THE_BEGINNING then
```
Comment (wrenffxi) [inline scripts/zones/Norg/npcs/Heillal.lua:14]:
```
require("scripts/globals/missions")
```

**Review by wrenffxi — CHANGES_REQUESTED** [review]

**Review by wrenffxi — APPROVED** [review]
