### PR TITLE
Fix abilities causing attack delays

### LINKED ISSUE #1146: Job Ability commands cause a delay in Auto attack even if they are on cool down.
<a href="https://github.com/SirGouki"></img></a> **Issue by [SirGouki](https://github.com/SirGouki)**
_Friday Mar 06, 2020 at 01:58:56_
_Originally opened as: project-topaz/topaz - Issue 403_

----

**_I have:_**

server branch: master

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

NOTE: I'm using the term delay in this context to refer to resetting auto attack, making you wait the full time till your next attack.

Reproduction:
  use /ja "" <t> to activate a job ability after it is on cool down, during combat.
  for example, attempt to steal from an enemy, then repeatedly use /ja "Steal" <t> or a macro that contains that.  You will never auto attack as this is resetting the auto attack delay even though the skill isn't firing (and not all JA's should be doing this in the first place i.e. dances allow you to attack while using them)

Expected:
  /ja commands should not be triggering a delay on Job Abilities that do not normally trigger a delay, nor should it be causing a delay if the JA is on cool down.  Retail does not do this.

This was first brought to my attention by Tankfest from Resolute, and it is happening on a clean Topaz-master server on my LAN, with all job abilities.

### PR DESCRIPTION
**Pull request by cocosolos**
Check if ability is on cooldown before changing state.

fixes #1146

**_I affirm:_**
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/topaz-next/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have read the [Contributing Guide](https://github.com/topaz-next/topaz/blob/release/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md)
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

**_Temporary_**:
- [x] that I understand there are large refactoring efforts going on right now, that these efforts touch every single Lua script and binding, and that my pull request might get put on hold to ensure there are not any conflicts with the refactoring work

### CODE REVIEW

File: src/map/ai/controllers/player_controller.cpp [hunk 1]
```diff
@@ -110,6 +111,12 @@ bool CPlayerController::Ability(uint16 targid, uint16 abilityid)
     auto* PChar = static_cast<CCharEntity*>(POwner);
     if (PChar->PAI->CanChangeState())
     {
+        CAbility* PAbility = ability::GetAbility(abilityid);
+        if (PChar->PRecastContainer->HasRecast(RECAST_ABILITY, PAbility->getRecastId(), PAbility->getRecastTime()))
```
Comment (zach2good) [inline src/map/ai/controllers/player_controller.cpp]: I believe `GetAbility` can fail and return `nullptr`, can you add a check for that?

Weaponskill does the same thing:
```cpp
        if (PWeaponSkill == nullptr)
        {
            PChar->pushPacket(new CMessageBasicPacket(PChar, PChar, 0, 0, MSGBASIC_CANNOT_USE_WS));
            return false;
        }
        ```

**Review by zach2good — APPROVED** [review]
Looks good, just needs one more check
