### PR TITLE
Fix additional dialog lines for Making the Grade quest

### LINKED ISSUE #2076: Windurst Quest "Making the Grade" Additional lines of dialogue
<a href="https://github.com/eyes-and-brain"></img></a> **Issue by [eyes-and-brain](https://github.com/eyes-and-brain)**
_Monday Oct 12, 2020 at 01:36:41_
_Originally opened as: project-topaz/topaz - Issue 1333_

----

**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

If the quest "Making the Grade" is QUEST_ACCEPTED the message of the NPC should change.

https://github.com/project-topaz/topaz/blob/ce4efc04260c6e325e044cc7e30226e705621d74/scripts/zones/Windurst_Waters/npcs/Pechiru-Mashiru.lua#L15-L25
```
    elseif (player:getQuestStatus(WINDURST, tpz.quest.id.windurst.MAKING_THE_GRADE) == QUEST_ACCEPTED) then
        player:startEvent(445)
```

https://github.com/project-topaz/topaz/blob/ce4efc04260c6e325e044cc7e30226e705621d74/scripts/zones/Windurst_Waters/npcs/Tauwawa.lua#L12-L14
```
require("scripts/globals/quests")

function onTrigger(player, npc)
    if (player:getQuestStatus(WINDURST, tpz.quest.id.windurst.MAKING_THE_GRADE) == QUEST_ACCEPTED) then
        player:startEvent(446)
    else
      player:startEvent(424)
    end
end
```

### PR DESCRIPTION
**Pull request by ghost**
**_I affirm:_**
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/topaz-next/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have read the [Contributing Guide](https://github.com/topaz-next/topaz/blob/release/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md)
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

**_Temporary_**:
- [x] that I understand there are large refactoring efforts going on right now, that these efforts touch every single Lua script and binding, and that my pull request might get put on hold to ensure there are not any conflicts with the refactoring work

Fixes #2076

### CODE REVIEW

File: scripts/zones/Windurst_Waters/npcs/Tauwawa.lua [hunk 1]
```diff
@@ -11,7 +11,11 @@ entity.onTrade = function(player, npc, trade)
 end
 
 entity.onTrigger = function(player, npc)
-    player:startEvent(424)
+    if player:getQuestStatus(tpz.quest.log_id.WINDURST, tpz.quest.id.windurst.MAKING_THE_GRADE) == QUEST_ACCEPTED then
```
Comment (wrenffxi) [inline scripts/zones/Windurst_Waters/npcs/Tauwawa.lua:15]:
```
require("scripts/globals/quests")
```

**Review by wrenffxi — CHANGES_REQUESTED** [review]

**Review by wrenffxi — APPROVED** [review]
