### PR TITLE
Time adjustments

### LINKED ISSUE #2532: Using os.date("%j") for "after midnight" checks has slim-but-possible chance to fail, exactly 1 year later
- [X] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Well, I'm on Dawn (PM8-4).

After I killed Promathia-the-weaker I did get Tear of Altana (key item), BUT...

It says to wait "Japanese Midnight", before to continue with the CSes.

Well, I went to sleep, I know perfectly well when J.M. is (yes, real time), of course I had to shutdown my computer.  Then when I decided to check (after over 16 hours IRL) I still didn't get any CS.  Then I decided to use !time command.  I used well over 24 hours (realtime world) to the game, and I'm still unable to get any CS.

What now?  Another bug?

### PR DESCRIPTION
**Pull request by cocosolos**
Fixed `getConquestTally` to give the correct timestamp and changed occurrences of `os.date` to the correct wait times for current retail. This means some stuff was changed to 60 seconds, some stuff was changed from "next day local time" to actual JP midnight, and other stuff with wait times was removed. Everything should be using a Unix timestamp, so shouldn't have any weird failures. Tested `getConquestTally` and the ROE 4-hour blocks.

Fixes #2532

**_I affirm:_**
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/topaz-next/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have read the [Contributing Guide](https://github.com/topaz-next/topaz/blob/release/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md)
- [ ] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

**_Temporary_**:
- [x] that I understand there are large refactoring efforts going on right now, that these efforts touch every single Lua script and binding, and that my pull request might get put on hold to ensure there are not any conflicts with the refactoring work

### CODE REVIEW

File: scripts/zones/Metalworks/npcs/Cid.lua [hunk 1]
```diff
@@ -53,7 +52,7 @@ entity.onTrigger = function(player, npc)
 
     if wsQuestEvent ~= nil then
         player:startEvent(wsQuestEvent)
-    elseif (currentCOPMission == tpz.mission.id.cop.DAWN and player:getCharVar("PromathiaStatus")==3 and player:getCharVar("Promathia_kill_day")~=currentday and player:getCharVar("COP_tenzen_story")== 0 ) then
+    elseif (currentCOPMission == tpz.mission.id.cop.DAWN and player:getCharVar("PromathiaStatus")==3 and player:getCharVar("Promathia_kill_day")<os.time() and player:getCharVar("COP_tenzen_story")== 0 ) then
```
Comment (TeoTwawki) [inline scripts/zones/Metalworks/npcs/Cid.lua]: can you reformat this line please? its wide and the operators have no spacing around them.

File: scripts/zones/Port_Windurst/npcs/Chipmy-Popmy.lua [hunk 2]
```diff
@@ -12,8 +12,7 @@ entity.onTrade = function(player, npc, trade)
 end
 
 entity.onTrigger = function(player, npc)
-    local currentday = tonumber(os.date("%j"))
-    if (player:getCurrentMission(COP) == tpz.mission.id.cop.DAWN and player:getCharVar("PromathiaStatus")==3 and player:getCharVar("Promathia_kill_day") ~= currentday and player:getCharVar("COP_3-taru_story")== 0 ) then
+    if (player:getCurrentMission(COP) == tpz.mission.id.cop.DAWN and player:getCharVar("PromathiaStatus")==3 and player:getCharVar("Promathia_kill_day") < os.time() and player:getCharVar("COP_3-taru_story")== 0 ) then
```
Comment (TeoTwawki) [inline scripts/zones/Port_Windurst/npcs/Chipmy-Popmy.lua]: here too if you don't mind

**Review by TeoTwawki — APPROVED** [review]
